require 'rubygems'
require 'rake'
require 'echoe'

Echoe.new('haul', '1.0') do |p|
	p.description		= "Haulage source code manager core module."
	p.url			= "http://stpettersens.github.com/Haulage"		
	p.email			= "s.stpettersen+github@gmail.com"
	p.ignore_pattern	= ["tmp/*", "script/*"]
	p.development_dependencies = []
end
